name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH and ngrok
      run: |
        sudo apt-get update
        sudo apt-get install -y ssh unzip
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
    - name: Extract ngrok
      run: tar xvzf ngrok.tgz
    - name: Auth ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Setup SSH User
      run: |
        sudo useradd -m -s /bin/bash -p $(echo '${{ secrets.SSH_USER_PASSWORD }}' | openssl passwd -1 -stdin) nasuh
        sudo service ssh start
    - name: Create Tunnel
      run: ./ngrok tcp 22 &
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
