name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
      
    - name: Extract ngrok
      run: tar xvzf ngrok.tgz
      
    - name: Auth ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
    - name: Setup SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
        sudo systemctl enable ssh
        sudo systemctl start ssh
        # Set custom user and password
        sudo useradd -m nasuh
        echo nasuh:7c91057D | sudo chpasswd
        sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        sudo systemctl restart sshd
        # Ensure ssh is running and accessible
        sudo ufw allow ssh
        
    - name: Create Tunnel
      run: |
        ./ngrok tcp 22 & sleep 10
        curl http://localhost:4040/api/tunnels | jq '.tunnels[] | select(.proto == "tcp") | .public_url'
